### ISSUE TITLE
 Avoid Repeating Styles when possible

### ISSUE THREAD

**Issue by zannain** [markthedesigner/prj-rev-bwfs-dasmoto#2]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is an important programming principle. If you find yourself repeating certain styles this is an indication that you can simplify your stylesheet by making use of CSS classes.

Rather than [applying](https://github.com/markthedesigner/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/CSS/style.css#L7) the following styles multiple times. 

```css
  font-weight: bold;
```
**Alternatives**
1. You can also create a style-specific class

```css
.bold {
   font-weight: bold;
 }
```
Now you can give multiple element tags a class attribute of `bold` and they will all receive this common style. This is in fact how CSS libraries such as [Bootstrap](https://getbootstrap.com/) work. 

3. [Using CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)

```css
:root {
    --default-font-weight: bold;
}

#paint {
     font-weight: var(--default-font-weight);
}
```

With any of these approaches, it's easy to update a style simultaneously by modifying that variable or the `.bold`/ selector and the entire page is updated.
